#!/bin/bash
# lightum-indicator script
# (c)2012 Pau Oliva Fora
# License: GPLv2+

# load include file
source /usr/share/lightum-indicator/lightum-indicator-include

# make sure indicator auto-starts
if [ ! -f "${HOME}/.config/autostart/lightum-indicator.desktop" ]; then
	mkdir -p ${HOME}/.config/autostart/
	cp /usr/share/applications/lightum-indicator.desktop ${HOME}/.config/autostart/lightum-indicator.desktop
fi

# make sure lightum is running, otherwise start it
pidof lightum 2>&1 >/dev/null || lightum

# update the menu file, if it doesn't exist
updatemenu

# launch cappind-lightum
/usr/share/lightum-indicator/cappind-lightum.py &
